services:
  web:
    container_name: webapp
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: ["/bin/sh", "/app/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=my_django_app.settings
      - POSTGRES_DB=jobboard
      - POSTGRES_USER=jobboarduser
      - POSTGRES_PASSWORD=jobboardpass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=adminpass
    depends_on:
      - db

  db:
    container_name: webapp_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: jobboard
      POSTGRES_USER: jobboarduser
      POSTGRES_PASSWORD: jobboardpass
    ports:
      - "5432:5432"

  pgadmin:
    container_name: webapp_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db